POST http://localhost:3003/api/blogs
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVlZmIzYzk1YTExYjg0NTJmNDFjNGMwNiIsImlhdCI6MTU5MzYwNDg1M30.PUFo4F7mLltsEhXdOoEL3TvzdZF4q-KAl2fp8o98aTM

{
    "title": "testitest",
    "author": "testauthor",
    "url": "testurl"
}