POST http://localhost:3001/api/blogs/5f280ca379932b3f1c058961/comments
content-Type: application/json

{
    "comments": ["nice", "boo", "ebin"],
    "title": "comment test",
    "author": "testauthor",
    "url": "testurl",
    "likes": 234
}