POST http://localhost:3001/api/blogs
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZjFlYWE2NmU5OGJkNTgxMWMxYTIyZWUiLCJpYXQiOjE1OTU4NTc0OTR9.LGKesH0DZAdeqEj60FQ0desk4FN9s9aUmjrpa0P6Fy8

{
    "title": "",
    "author": "testauthor",
    "url": "testurl"
}